### ISSUE TITLE
Don't understand where this fits into the TestCafe flow

### ISSUE THREAD

**Issue by dsudia** [DevExpress/TestCafe-BrowserStack#11]
@LavrovArtem @churkin 

I'm just starting to use TestCafe as an alternative to [Webdriver.io](http://webdriver.io) so forgive me if the answer is obvious and I don't see it.

Could you provide an example of how this would be used? Does it need to be included in the test file before a fixture is defined? Is it put in its own file and fired off using the --app command? Any guidance would be most appreciated, thank you! 

And thanks for building this out! I thought I was going to have to!

**Comment by churkin** [comment]
Hi @dsudia,
Thank you for your interest in our product! Unfortunately, this module is designed to work with the old version of TestCafe - [15.3](https://testcafe.devexpress.com/). I understand that you use the [new](https://github.com/DevExpress/testcafe) open source version. For it, we have a [plug-in](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browser-support.html#browsers-in-cloud-testing-services) only for [Sauce Labs](https://saucelabs.com/) service. But we are planning to add a plug-in for `Browser Stack` too.

Please contact us if you have questions.

**Comment by crazy4groovy** [comment]
I was also confused by this... the explanation you provided above in the Readme would be 100% helpful. (as would a plug-in) :wink:
