### ISSUE TITLE
How to run index.json

### ISSUE THREAD

**Issue by guptaakhil** [DevExpress/TestCafe-BrowserStack#14]
May be it stupid question but i am quite new in automaiton. please guide me how can i run my test using workder , not able to ccreate worker giveing http error. Can any one help me in this

**Comment by guptaakhil** [comment]
Please help me to run this , able to run workder but no test launch as don't know test cafe run with test case not run as indivdual command.

**Comment by FDiskas** [comment]
You can try https://github.com/DevExpress/testcafe-browser-provider-browserstack
